### ISSUE TITLE
Plotting Colour Schemes

### ISSUE THREAD

**Issue by danielparthier** [danielparthier/BehaviourAnalysis#3]
I am currently finishing up functions for the package and am introducing plotting functions.
The ones I have now are trying to be colourblind friendly and at the same time should allow for better readability especially when it comes to "object approach angles". It would be nice to get your feedback and maybe other ideas to implement. @hung-lo @johntukker @natglo 

![MovementPlotDark](https://user-images.githubusercontent.com/40452990/77227263-54720a80-6b7f-11ea-9fd0-712ece0cd566.jpeg)
![MovementPlotLight](https://user-images.githubusercontent.com/40452990/77227270-55a33780-6b7f-11ea-8627-0f67d30fa359.jpeg)

**Comment by danielparthier** [comment]
The updates are in the "package" [branch](https://github.com/danielparthier/BehaviourAnalysis/tree/package)

**Comment by hung-lo** [comment]
Hi Daniel,
so viridis is a good color map in general, I also like it.
For the diverging color map, the upper one is extremely difficult for me to distinguish. So I'd prefer the one down below. If there are other options, I think the 'bwr', 'seismic', and 'PuOr' are all good for me.
![image](https://user-images.githubusercontent.com/52919026/77229941-06660280-6b91-11ea-867e-936cba2e4c21.png)

Thank you very much for being inclusive :)

Hung

**Comment by hung-lo** [comment]
Btw have you thought about adding titles to subplots? I also find that much easier to interpret. Especially for the angles to object 1 and 2, I assume B is OBj_1 and C is Obj_2 but it can be clearer :)

**Comment by danielparthier** [comment]
I can add titles but didn't think of a final figure thing here. But you are right about it an I will change it. ;)
The problem with these is that at the midpoint they go to white which is problematic on a white surface and a path. In principle I can construct any scheme you think makes sense. I would just need the HEX code for some parts (e.g. start/end/midpoint or even 75% etc.).
My problem really is that the 0° should be visible as a path so I was hoping the yellowish ones are fine. I looked at some colour scheme [generator](https://colorbrewer2.org/#type=diverging&scheme=RdYlBu&n=5) (different conditions) online to find something which could work but apparently I was wrong!

**Comment by danielparthier** [comment]
> Btw have you thought about adding titles to subplots? I also find that much easier to interpret. Especially for the angles to object 1 and 2, I assume B is OBj_1 and C is Obj_2 but it can be clearer :)

I just thought about it. Maybe it would make sense to be able to highlight the object (different colour for circle) or is a title always the better option. I could add an option in the function which automatically highlights this.

**Comment by hung-lo** [comment]
You're completely right about the midpoint disappearing issue here, I'll think about which color map will make more sense here...

And for adding titles, I think highlighting the objects itself is a great idea (like full color for the focussed one and alpha=0.2 for the other one or something like that). If it's clear enough, I don't think the titles will be that necessary. But of course that's only my opinion, let's wait a bit and see how others think about this :)

Thanks a lot!

**Comment by danielparthier** [comment]
The function `AnglePlot()` was updated and now takes `ObjectHighlight` with `"none"`, `"alpha"`, `"stroke"`, and `"colour"` as input argument.
![AnglePlotObjectIdentification](https://user-images.githubusercontent.com/40452990/77771866-8daaee80-7047-11ea-84af-9deafebd834a.png)

**Comment by danielparthier** [comment]
Now it's also possible to parse a colour string to the function to take the colour of your choosing.
![colourOverview](https://user-images.githubusercontent.com/40452990/77775356-bbdefd00-704c-11ea-897e-ebdcd97e1375.png)
